config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
    resources :likes
  end


  devise_for :users,  controllers: { sessions: 'users/sessions' }

  resources :users do
    member do
      get :add_friend
      get :un_friend 
      get :accept
      get :cancel
      get :friend
    end
  end
  
  get 'welcome/index'

  root 'welcome#index'

   # resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  has_many :likes, dependent: :destroy

  acts_as_followable
  acts_as_follower

   paginates_per 5
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable

    def username
       return self.email.split('@')[0].capitalize
    end 

    def is_accepted?(current_user, user)
      Follow.where(follower_id: current_user.id, followable_id: user.id).first.try(:isaccepted)
      # puts '@@@@@@@@@@@@@@@@'
      # puts current_user.inspect
      # puts user.inspect
      # puts '@@@@@@@@@@@@@@@@'
      # # @user = User.find(params[:id])
      # # puts self.follow
      # @accept = Follow.where(follower_id: current_user.id, followable_id: @user.id, isaccepted: true)
      # return @accept
    end

    def get_friendship_status(user)
      relationship = Follow.find_by(follower_id: self.id, followable_id: user.id) || Follow.find_by(follower_id: user.id, followable_id: self.id)
      if relationship
        if relationship.isaccepted
          return "friend"
        else
          return "pending"
        end
      else
        return "not yet"
      end
    end
   
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.where.not(id: current_user.id).page(params[:page]).per(10)
  end 

  def show
    @user = User.find_by_id(params[:id])
  end

  def add_friend
    @user = User.find(params[:id])
    #current_user == @user
    current_user.follow(@user)
    @follow = Follow.find_by(follower: current_user, followable: @user)
    respond_to do |format|
       format.js 
    end
  end

  def un_friend
    @user = User.find(params[:id])
    current_user.stop_following(@user) || @user.stop_following(current_user) 
     respond_to do |format|
       format.js 
      end
  end

  
  def accept
    puts params
    @user = User.find(params['user']) 
    @current_user = User.find(params[:id]) 
    @follow = Follow.find_by(follower_id: @user.id, followable_id: @current_user.id)
    @follow.update(isaccepted: true)
     respond_to do |format|
       format.js 
     end
  end

   def cancel
    @user = User.find(params['user']) 
    @current_user = User.find(params[:id])
     #@current_user.stop_following(@user)
    @follow = Follow.find_by(follower_id: @user.id, followable_id: @current_user.id)
    @follow.destroy
      respond_to do |format|
       format.js 
      end
   end

   #def friend
    #@friends = Follow.where(followable_id: current_user, isaccepted: true)
    # puts '*********'

     #puts @friends.inspect
     #puts '@@@@@@@@@@'
     #render 'friend'
   #end

  
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.email, class: "gravatar")
  end

end

app/views/users/_add_friend_button.html.erb
<div id="add">
  <%= button_to "Add Friend", {action: 'add_friend', id: user.id}, method: 'get', class: 'btn btn-primary btn-add-friend header-align', remote: true %>
</div>

app/views/users/_cancel.html.erb
<h1> Cancel </h1>

app/views/users/_friend.html.erb
<h1> Friend </h1>

app/views/users/_pending_button.html.erb
<div id="pending">
  <%= button_to "Cancel Request", {action: 'un_friend', id: user.id}, method: 'get', class: 'btn btn-primary btn-add-friend header-align', remote: true %>
</div>

app/views/users/_request.html.erb
      
 <div id="accept">
  <%= link_to "Accept",  accept_user_path(curent_user: current_user.id, user: requested_user.id) ,remote: true ,class: "btn btn-sm btn-success"%> |   
  <%= link_to "Decline", cancel_user_path(curent_user: current_user.id, user: requested_user.id) ,remote: true,class: "btn btn-sm btn-danger"%>
</div>

app/views/users/accept.js.erb
$("#accept").html("<%= escape_javascript(render 'friend') %>");

app/views/users/add_friend.js.erb
$("#user-<%=@user.id%>").html("<%= escape_javascript(render partial: 'pending_button', locals: { user: @user } ) %>");

app/views/users/cancel.js.erb
$("#accept").html("<%= escape_javascript(render 'cancel') %>");

app/views/users/friend.html.erb
<h1>All Friend</h1>


<ul class="users">
  <% @friends.each do |user| %>
    <li>
    
     <%= user.follower.username %><br/>
     <%= user.follower.email %><br/>
   </li>
     
 <% end %>
</ul> 




  

app/views/users/index.html.erb
<h1>All users</h1>

<% #@users  User.all %>
<ul class="users">
  <% @users.each do |user| %>
    <li>
     <%= gravatar_for user, size: 50 %>
     <%= user.username %><br/>
     <%= user.email %><br/>
  
    <div class="follow-button-area" id="user-<%=user.id%>" style="float: right">
      <% if current_user.get_friendship_status(user) == "friend"  %>
        <div id="cancel">
          <%= button_to "Unfriend", {action: 'un_friend', id: user.id}, method: 'get' ,class: 'btn btn-secondary btn-unfriend header-align', remote: true %>
        </div>
      <% elsif  current_user.get_friendship_status(user) == "pending" %>
        <%= render 'pending_button', user: user %>
      <% elsif current_user.get_friendship_status(user) == "not yet" %>
        <%= render 'add_friend_button', user: user %>
      <% end %>
    </div>
    </li>

  <% end %>
</ul>   
  



<%= paginate @users %>

app/views/users/show.html.erb
<!--<h1><%= current_user.email %></h1>-->
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= current_user.email %>
      </h1>
    </section>
  </aside>
</div>


  <% Follow.where(followable_id: current_user, isaccepted: false).each do |request| %>
    <h4>You have new friend requests from:</h4>
    <li>
      <%= request.follower.email %> 
     <%= render 'request', :requested_user => request.follower %> 
   
    </li>
  <% end %>

app/views/users/un_friend.js.erb
$("#user-<%=@user.id%>").html("<%= escape_javascript(render partial: 'add_friend_button', locals: { user: @user } ) %>");