config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
    resources :likes
  end


  devise_for :users,  controllers: { sessions: 'users/sessions' }

  resources :users do
    member do
      get :add_friend
      get :un_friend 
      get :accept
      get :cancel
      get :friend
    end
  end
  
  get 'welcome/index'

  root 'welcome#index'

   # resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  mount_uploader :picture, PictureUploader
  has_many :comments
  has_many :likes, dependent: :destroy
  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  
  end

  # GET /posts/new
  def new
    @post = Post.new
    @comment = Comment.new
    @comment.post_id = @post.id
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:content, :picture)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
  <span class="picture">
    <%= form.file_field :picture %>
  </span>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= post.user.username %></td>
        <td><%= time_ago_in_words(post.created_at) %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></td>
        <% if post.user.id == current_user.id %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



<%= link_to 'New Post', new_post_path , class: "btn btn-lg btn-primary" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @post.content %>
  <%= image_tag @post.picture.url if @post.picture? %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.username %>
</p>

<p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>

<% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
<div class="center">
  <% if pre_like %>
    <%= button_to 'Unlike', post_like_path(@post, pre_like), method: :delete , class: "btn btn-lg btn-primary" %>
  <% else %>
    <%= button_to 'Like', post_likes_path(@post), method: :post, class: "btn btn-lg btn-primary" %>
  <% end %>

  <br>
   <h1><%= @post.comments.count %> Comments</h1>
        <%= render @post.comments %>
    
    <h3> Add a Comments: </h3>
     <%= link_to 'Comment', new_post_comment_path(@post) ,class: "btn btn-sm btn-success"%> 
  <br>

  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>
</div>