config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
    resources :likes
  end


  devise_for :users,  controllers: { sessions: 'users/sessions' }

  resources :users do
    member do
      get :add_friend
      get :un_friend 
      get :accept
      get :cancel
      get :friend
    end
  end
  
  get 'welcome/index'

  root 'welcome#index'

   # resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Mate app", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
          
            <% if !current_user.nil? %>
            <!--<li><%= link_to "Friend",  friend_user_path(current_user)%></li>-->
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                 <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>  
              </li>
            </ul>
          </li>
        <% else %>
          
            <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">.
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>